#!/bin/sh

### BEGIN INIT INFO
# Provides:          linuxsampler
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LinuxSampler
# Description:       LinuxSampler
### END INIT INFO

DAEMON="/usr/bin/linuxsampler"
DAEMON_NAME=linuxsampler
DAEMON_OPTS=""
DAEMON_USER=pi
DAEMON_LOGFILE=/var/log/$DAEMON_NAME.log
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    echo "Starting..." >> $DAEMON_LOGFILE
    $DAEMON $DAEMON_OPTS >> $DAEMON_LOGFILE 2>&1 &
    while ! echo exit | /usr/bin/netcat localhost 8888; do sleep 2; done
    netcat localhost 8888 < /etc/linuxampler.lscp
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    echo "Stopping..." >> $DAEMON_LOGFILE
    start-stop-daemon --stop --exec $DAEMON --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

